### ISSUE TITLE
How to override the values in the chart ?

### ISSUE THREAD

**Issue by shettyh** [operator-framework/helm-app-operator-kit#35]
Tried adding the values in the spec, like this 

```
apiVersion: xyz.com/v1alpha1
kind: Xyz
metadata:
  name: xyz.com
  labels:
    app: xyz
spec:
  size: 1
  global:
    host: x.x.x.x
    serviceA:
      enabled: false
```

But the chart is not using those values when installed. 

Can anyone please tell me how to properly set the values for the chart with `CR` ?

Thanks in advance
