### ISSUE TITLE
Read config file to support multiple charts simultaneously

### ISSUE THREAD

**Issue by joelanford** [operator-framework/helm-app-operator-kit#41]
To make this operator more versatile, it could be updated to support watching multiple CRs, each mapped to a different Helm chart directory based on the contents of a config file, much like `github.com/water-hole/ansible-operator`

Something like this:
```yaml
---

- group: example.com
  version: v1alpha1
  kind: MyApp
  chart: /charts/myapp

- group: example.com
  version: v1alpha1
  kind: MyDatabase
  chart: /charts/mydatabase
```

I'd propose adding a new environment variable (e.g. `HELM_WATCHES_FILE`). If it is present and set, read the mapping config from it. If not, just fall back to the existing environment variables to maintain backward compatibility.

It looks pretty straightforward to update `register.go` to expose a function to dynamically add new types to the scheme, and to update `helm.go` to use a GVK -> chartDir lookup rather than a static `chartDir` setting. 

Thoughts?
